### ISSUE TITLE
No call caching results shown when nested scatters in workflow

### ISSUE THREAD

**Issue by vortexing** [FredHutch/shiny-cromwell#4] opened 2022-01-27 17:30 UTC
For some reason only the first level of scattered tasks and any unscattered tasks seem to be showing up in the call caching table in the app.   So scatters of scatters do NOT show up.

**Comment by tefirman** [comment] 2024-07-22 21:37
@vortexing -- how can we reproduce this problem? Pretty old issue, just hoping to get more context.

**Comment by tefirman** [comment] 2024-07-29 18:17
Tried reproducing this with a modified version of [helloDockerHostname.wdl](https://github.com/getwilds/ww-test-workflows/blob/main/helloDockerHostname/helloDockerHostname.wdl) (see below) and it seems to pull previous results from the cache just fine. Wondering if maybe it had to do with how the Docker image was getting pulled, but regardless, I'm going to assume this issue has been fixed in the time since it was filed. Closing as "not planned".

```
workflow HelloDockerHostname {
  scatter (idx in range(5)) {
    scatter (idx in range(5)) {
        call Hostname {}
    }
  }

  output {
    Array[Array[File]] stdout = Hostname.out
  }

  parameter_meta {
    stdout: "hostname of the node the job was submitted to"
  }
}
```

**Closed by tefirman** 2024-07-29 18:17 UTC
Labels: wontfix
