### ISSUE TITLE
Abort a workflow : autopopulates with user id

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/shiny-cromwell#70] opened 2024-02-27 18:37 UTC
Abort workflow tab gets autopopulated with my user name. 
Would be nice to have it not do that!

**Comment by sckott** [comment] 2024-02-27 18:45
Thanks! 

I'm not seeing that happen on my end. It's possible that was leftover from a previous session of using the app?

**Comment by sitapriyamoorthi** [comment] 2024-02-27 18:47
No i had shut down my PROOF-cromwell server. So this was a a new sesh

**Comment by sckott** [comment] 2024-02-27 18:48
I mean a new session of the app - by session i mean browser session.

**Comment by sckott** [comment] 2024-02-28 18:17
AFAICT this was probably just a transient issue - closing - let me know if you see this again and we can reopen this

**Comment by sckott** [comment] 2024-02-29 00:12
still happening apparently. just for Sita so far. 

Not sure how it can happen.

**Comment by tefirman** [comment] 2024-07-24 06:17
Haven't seen this since February, wondering if this was maybe the Chrome browser errantly autofilling? Regardless, closing for now and can reopen if it pops back up.

**Closed by tefirman** 2024-07-24 06:17 UTC
Labels: wontfix

**Comment by sitapriyamoorthi** [comment] 2024-07-24 14:05
![Screenshot 2024-07-24 at 7 05 46 AM](https://github.com/user-attachments/assets/8683881f-2c9e-40e1-9a9c-9bb7d25b9e8e)
Issue persists.

**Comment by sckott** [comment] 2024-07-24 19:56
a few thoughts

- It's definitely not ideal, but in the larger picture perhaps isn't a big deal? BUT, if you think it is an important thing Sita, do speak up
- This is Shiny specific, so if we're going to abandon Shiny soon then might be worth ignoring it
- I still can't reproduce this. If someone can give some kind of lead on this then we can try to address it

**Comment by sitapriyamoorthi** [comment] 2024-07-24 21:52
Totally upto you all. I am just here to raise things as I see it. Its not an "issue" per se.. but more of a cosmetic aspect. I just go to abort worflows and it is autopopulated with this.
