### ISSUE TITLE
unnecessary polling?

### ISSUE THREAD

**Issue by dtenenba** [FredHutch/shiny-cromwell#89] opened 2024-04-23 17:13 UTC
When a user is logged in to proof.fredhutch.org and on the PROOF Server tab, the shiny app [polls](https://github.com/FredHutch/shiny-cromwell/blob/0247d49198f7835cde86ca38e28e56f9cf7f81bc/app/server.R#L286) the GET /cromwell-server endpoint of the PROOF API every 2 seconds.

Usually the API can handle this. Occasionally there are problems and I have some ideas about fixing them on the API side.

But I am wondering if this polling is necessary. I could be wrong, but I think calling this endpoint is only *really* necessary when

* starting a PROOF Cromwell server (to make sure one is not up already); after starting, this is the only time we may want to poll (and we'd stop when the server comes up)
* before running any operation that requires a cromwell server be up. 
* Before stopping a cromwell server 

If I am not mistaken about this, then it seems wrong to continue polling every 2 seconds. 

What do people think? If there is agreement maybe we can change this.

**Comment by dtenenba** [comment] 2024-04-23 17:36
If polling is unavoidable, maybe we can look into having a long running connection, such as with websockets, or(probably a better fit for a REST API) Server-Sent Events (SSE).

**Comment by sckott** [comment] 2024-07-08 21:57
See also #75

**Comment by sckott** [comment] 2024-07-08 22:12
In #75 I changed polling to only happen when the user is actively on the **PROOF Server** tab, so that's some improvement. 

> we just send something from the server to the client when there is an update.

I don't know if Shiny can do this. Maybe it can. I've tried longer times between polling requests, but the issue is that creates a what I think is too long of a lag where the user assumes nothing is happening or something didn't work. 

>  but I think calling this endpoint is only really necessary when

In your list of 3 scenarios that's not quite right. The polling is only done to get metadata from the PROOF API on the server status. Polling doesn't have to be done before or after starting or stopping a server. In theory we could remove the metadata from this page altogether and remove the polling code, but I don't think we want to remove the information on the user's server.

**Comment by tefirman** [comment] 2024-07-26 21:42
If I'm understanding the discussion above, this feels like a v2.0 discussion since it only applies to a relatively small use case and functions relatively well as is. Plus, moving the app out of Shiny in v2.0 might alleviate this issue entirely. But I might be underestimating the occasional API problems that @dtenenba mentioned. Mind if I close this issue for now and we can reopen it if those API problems start becoming more prevalent?

**Comment by dtenenba** [comment] 2024-07-27 19:38
OK with me to close this. I did a bunch of testing and was not able to definitively prove or disprove that this was a problem or related to the problems we saw in the stress test.
We may want to reopen if further evidence surfaces either way.

**Closed** 2024-07-28 05:13 UTC
Labels: investigating
